theme: blowfish
defaultContentLanguage: en
enableRobotsTXT: yes
paginate: 10
summaryLength: 0
buildDrafts: no
buildFuture: no
imaging:
  anchor: Center
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
outputs:
  home:
    - HTML
    - RSS
    - JSON
related:
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 100
    - name: series
      weight: 50
    - name: authors
      weight: 20
    - name: date
      weight: 10
    - applyFilter: no
      name: fragmentrefs
      type: fragments
      weight: 10
  threshold: 0
  toLower: no
